dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies (3rd and 4th pip calls just for GPKit integration)
install:
  - pip install --verbose numpy>=1.16.5
  - pip install --verbose scipy>=1.1 ecos>=2 coveralls
  - pip install nose2[coverage_plugin]
  - pip install pint cvxopt ad
  - pip install gpkit==0.9.9.2
  - python setup.py install
# command to run tests (import gpkit, since it builds on first import).
script:
  - python -c "import gpkit"
  - nose2 --with-coverage --coverage-config=.coveralls_publish_config
  - coveralls --rcfile=.coveralls_publish_config
