dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies (2nd and 3rd pip calls just for GPKit integration)
install:
  - pip install scipy>=1.1 numpy>=1.14 ecos>=2 nose2 coverage coveralls
  - pip install pint cvxopt ad
  - pip install gpkit
  - python setup.py install
# command to run tests (import gpkit, since it builds on first import).
script:
  - python -c "import gpkit"
  - nose2 --with-coverage --coverage-config=.coveralls_publish_config
  - coveralls --rcfile=.coveralls_publish_config
